name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
          cache: 'pnpm'

      - name: Set up .npmrc
        env:
          GSAP_AUTH_TOKEN: ${{ secrets.GSAP_AUTH_TOKEN }}
        run: |
          echo "registry=https://npm.greensock.com" > .npmrc
          echo "//npm.greensock.com/:_authToken=${GSAP_AUTH_TOKEN}" >> .npmrc

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Next.js Application
        run: pnpm run build
